"""init after refactoring

Revision ID: 20260709_0001
Revises:
Create Date: 2026-07-09 13:40:31.702953
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = "20260709_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_vendor",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "import_source",
        sa.Column("vendor_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vendor_code"], ["import_vendor.code"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vendor_code", "name", name="uq_import_source_vendor_name"),
    )
    op.create_index(
        op.f("ix_import_source_vendor_code"),
        "import_source",
        ["vendor_code"],
        unique=False,
    )
    op.create_table(
        "source_snapshot",
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("artifact_hash", sa.String(length=64), nullable=True),
        sa.Column("source_format", sa.String(length=64), nullable=True),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["import_source.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_snapshot_artifact_hash"),
        "source_snapshot",
        ["artifact_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_snapshot_source_id"),
        "source_snapshot",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "canonical_snapshot",
        sa.Column("source_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("normalizer_code", sa.String(length=64), nullable=False),
        sa.Column("normalizer_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("zones_total", sa.Integer(), nullable=False),
        sa.Column("objects_total", sa.Integer(), nullable=False),
        sa.Column("rules_total", sa.Integer(), nullable=False),
        sa.Column("issues_total", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"], ["source_snapshot.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_snapshot_id",
            "normalizer_code",
            "normalizer_version",
            name="uq_canonical_snapshot_source_normalizer",
        ),
    )
    op.create_index(
        op.f("ix_canonical_snapshot_source_snapshot_id"),
        "canonical_snapshot",
        ["source_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "import_upload",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("uploaded_by", sa.String(length=128), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("raw_mime_type", sa.String(length=128), nullable=True),
        sa.Column("resolved_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resolved_snapshot_id"], ["source_snapshot.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["import_source.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_upload_artifact_hash"),
        "import_upload",
        ["artifact_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_upload_source_id"), "import_upload", ["source_id"], unique=False
    )
    op.create_table(
        "source_artifact",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["source_snapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_table(
        "canonical_issue",
        sa.Column("canonical_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_key", sa.String(length=255), nullable=True),
        sa.Column("issue_code", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("source_line_start", sa.Integer(), nullable=True),
        sa.Column("source_line_end", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_snapshot_id"], ["canonical_snapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_canonical_issue_canonical_snapshot_id"),
        "canonical_issue",
        ["canonical_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "canonical_object",
        sa.Column("canonical_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.String(length=255), nullable=False),
        sa.Column("object_family", sa.String(length=32), nullable=False),
        sa.Column("object_kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("ip_version", sa.SmallInteger(), nullable=True),
        sa.Column("cidr", sa.String(length=64), nullable=True),
        sa.Column("range_start", postgresql.INET(), nullable=True),
        sa.Column("range_end", postgresql.INET(), nullable=True),
        sa.Column("fqdn", sa.String(length=255), nullable=True),
        sa.Column("protocol", sa.String(length=16), nullable=True),
        sa.Column("port_from", sa.Integer(), nullable=True),
        sa.Column("port_to", sa.Integer(), nullable=True),
        sa.Column("icmp_type", sa.SmallInteger(), nullable=True),
        sa.Column("icmp_code", sa.SmallInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_snapshot_id"], ["canonical_snapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_canonical_object_canonical_snapshot_id"),
        "canonical_object",
        ["canonical_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_object_object_family"),
        "canonical_object",
        ["object_family"],
        unique=False,
    )
    op.create_table(
        "canonical_rule",
        sa.Column("canonical_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("rule_key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_snapshot_id"], ["canonical_snapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_canonical_rule_canonical_snapshot_id"),
        "canonical_rule",
        ["canonical_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_rule_priority"), "canonical_rule", ["priority"], unique=False
    )
    op.create_table(
        "canonical_zone",
        sa.Column("canonical_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("zone_key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("direction_hint", sa.String(length=16), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_snapshot_id"], ["canonical_snapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_canonical_zone_canonical_snapshot_id"),
        "canonical_zone",
        ["canonical_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "mapping_scope",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("canonical_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("sdwan_target_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_snapshot_id"], ["canonical_snapshot.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trace_raw_to_canonical",
        sa.Column("source_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("canonical_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("vendor_code", sa.String(length=64), nullable=False),
        sa.Column("normalizer_code", sa.String(length=64), nullable=False),
        sa.Column("normalizer_version", sa.String(length=32), nullable=False),
        sa.Column("source_line_start", sa.Integer(), nullable=False),
        sa.Column("source_line_end", sa.Integer(), nullable=False),
        sa.Column("source_fragment", sa.Text(), nullable=True),
        sa.Column("canonical_kind", sa.String(length=32), nullable=False),
        sa.Column("canonical_id", sa.UUID(), nullable=False),
        sa.Column("canonical_role", sa.String(length=32), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "source_line_start >= 1 AND source_line_end >= source_line_start",
            name="ck_trace_r2c_line_range",
        ),
        sa.ForeignKeyConstraint(
            ["canonical_snapshot_id"], ["canonical_snapshot.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"], ["source_snapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_trace_r2c_canonical_snapshot",
        "trace_raw_to_canonical",
        ["canonical_snapshot_id", "canonical_kind"],
        unique=False,
    )
    op.create_index(
        "ix_trace_r2c_created_at",
        "trace_raw_to_canonical",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_trace_r2c_source_snapshot_line",
        "trace_raw_to_canonical",
        ["source_snapshot_id", "source_line_start"],
        unique=False,
    )
    op.create_index(
        "ix_trace_r2c_target",
        "trace_raw_to_canonical",
        ["canonical_kind", "canonical_id"],
        unique=False,
    )
    op.create_table(
        "canonical_object_member",
        sa.Column("parent_object_id", sa.UUID(), nullable=False),
        sa.Column("child_object_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_object_id"], ["canonical_object.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_object_id"], ["canonical_object.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_canonical_object_member_parent_object_id"),
        "canonical_object_member",
        ["parent_object_id"],
        unique=False,
    )
    op.create_table(
        "canonical_rule_operand",
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("operand_role", sa.String(length=32), nullable=False),
        sa.Column("target_zone_id", sa.UUID(), nullable=True),
        sa.Column("target_object_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "((target_zone_id IS NOT NULL)::int + (target_object_id IS NOT NULL)::int) = 1",
            name="ck_canonical_rule_operand_single_target",
        ),
        sa.ForeignKeyConstraint(["rule_id"], ["canonical_rule.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_object_id"], ["canonical_object.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["target_zone_id"], ["canonical_zone.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_canonical_rule_operand_operand_role"),
        "canonical_rule_operand",
        ["operand_role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_rule_operand_rule_id"),
        "canonical_rule_operand",
        ["rule_id"],
        unique=False,
    )
    op.create_table(
        "execute_plan",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mapping_scope_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mapping_scope_id"], ["mapping_scope.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mapping_entity_result",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mapping_scope_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("canonical_zone_id", sa.UUID(), nullable=True),
        sa.Column("canonical_object_id", sa.UUID(), nullable=True),
        sa.Column("result_status", sa.String(length=32), nullable=False),
        sa.Column("selection_method", sa.String(length=64), nullable=True),
        sa.Column("selected_sdwan_entity_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_object_id"], ["canonical_object.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["canonical_zone_id"], ["canonical_zone.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["mapping_scope_id"], ["mapping_scope.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mapping_scope_rule",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mapping_scope_id", sa.UUID(), nullable=False),
        sa.Column("canonical_rule_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_rule_id"], ["canonical_rule.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["mapping_scope_id"], ["mapping_scope.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "execute_plan_rule",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execute_plan_id", sa.UUID(), nullable=False),
        sa.Column("mapping_scope_rule_id", sa.UUID(), nullable=False),
        sa.Column(
            "draft_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("matched_sdwan_rule_id", sa.Integer(), nullable=True),
        sa.Column("match_status", sa.String(length=32), nullable=False),
        sa.Column("match_info", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execute_plan_id"], ["execute_plan.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["mapping_scope_rule_id"], ["mapping_scope_rule.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mapping_entity_candidate",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("result_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("sdwan_entity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_id"], ["mapping_entity_result.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mapping_scope_rule_operand",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mapping_scope_rule_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("mapping_entity_result_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_entity_result_id"],
            ["mapping_entity_result.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mapping_scope_rule_id"], ["mapping_scope_rule.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Predefined tables data

    op.execute("""
        INSERT INTO import_vendor (code, display_name, active)
        SELECT DISTINCT s.vendor_code, s.vendor_code, true
        FROM import_source s
        WHERE s.vendor_code IS NOT NULL
        ON CONFLICT (code) DO NOTHING
        """)
    op.execute("""
        INSERT INTO import_vendor (code, display_name, active)
        VALUES ('cisco_asa', 'Cisco ASA', true)
        ON CONFLICT (code) DO NOTHING
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mapping_scope_rule_operand")
    op.drop_table("mapping_entity_candidate")
    op.drop_table("execute_plan_rule")
    op.drop_table("mapping_scope_rule")
    op.drop_table("mapping_entity_result")
    op.drop_table("execute_plan")
    op.drop_index(
        op.f("ix_canonical_rule_operand_rule_id"), table_name="canonical_rule_operand"
    )
    op.drop_index(
        op.f("ix_canonical_rule_operand_operand_role"),
        table_name="canonical_rule_operand",
    )
    op.drop_table("canonical_rule_operand")
    op.drop_index(
        op.f("ix_canonical_object_member_parent_object_id"),
        table_name="canonical_object_member",
    )
    op.drop_table("canonical_object_member")
    op.drop_index("ix_trace_r2c_target", table_name="trace_raw_to_canonical")
    op.drop_index(
        "ix_trace_r2c_source_snapshot_line", table_name="trace_raw_to_canonical"
    )
    op.drop_index("ix_trace_r2c_created_at", table_name="trace_raw_to_canonical")
    op.drop_index(
        "ix_trace_r2c_canonical_snapshot", table_name="trace_raw_to_canonical"
    )
    op.drop_table("trace_raw_to_canonical")
    op.drop_table("mapping_scope")
    op.drop_index(
        op.f("ix_canonical_zone_canonical_snapshot_id"), table_name="canonical_zone"
    )
    op.drop_table("canonical_zone")
    op.drop_index(op.f("ix_canonical_rule_priority"), table_name="canonical_rule")
    op.drop_index(
        op.f("ix_canonical_rule_canonical_snapshot_id"), table_name="canonical_rule"
    )
    op.drop_table("canonical_rule")
    op.drop_index(
        op.f("ix_canonical_object_object_family"), table_name="canonical_object"
    )
    op.drop_index(
        op.f("ix_canonical_object_canonical_snapshot_id"), table_name="canonical_object"
    )
    op.drop_table("canonical_object")
    op.drop_index(
        op.f("ix_canonical_issue_canonical_snapshot_id"), table_name="canonical_issue"
    )
    op.drop_table("canonical_issue")
    op.drop_table("source_artifact")
    op.drop_index(op.f("ix_import_upload_source_id"), table_name="import_upload")
    op.drop_index(op.f("ix_import_upload_artifact_hash"), table_name="import_upload")
    op.drop_table("import_upload")
    op.drop_index(
        op.f("ix_canonical_snapshot_source_snapshot_id"),
        table_name="canonical_snapshot",
    )
    op.drop_table("canonical_snapshot")
    op.drop_index(op.f("ix_source_snapshot_source_id"), table_name="source_snapshot")
    op.drop_index(
        op.f("ix_source_snapshot_artifact_hash"), table_name="source_snapshot"
    )
    op.drop_table("source_snapshot")
    op.drop_index(op.f("ix_import_source_vendor_code"), table_name="import_source")
    op.drop_table("import_source")
    op.drop_table("import_vendor")
    # ### end Alembic commands ###
